### ISSUE TITLE
different arguments handling of `.use` method

### ISSUE THREAD

**Issue by tunnckoCore** [node-base/base-plugins#5]
I'm working on fix the compatibility issue that currently `minibase-create-plugin` v2 has.

The only main difference between our plugin systems is 1) that Base's default `.use` don't support passing plugin options as 2nd argument; 2) base-plugins passes plugin options as third argument. So okey, I can fix that, based on `app.isBase` and `app.isRegistered('base-plugins')`, but there's a little problem.

In short: I believe that this last case here should be working too

```js
base.use(fn, options) // work
base.use(name, fn, options) // work
base.use(fn, undefined/or/falsey, options) // not work
```

which forces me to make ugly things and add more branches to the code

```js
app.use(name, fn || opts, opts)
```

edit:

In any way, now you can use `minibase-create-plugin` >=v2 to create Base plugins too, with included registering using isRegistered :)

**Comment by jonschlinkert** [comment]
> The only main difference between our plugin systems is 1) that Base's default .use don't support passing plugin options as 2nd argument; 2) base-plugins passes plugin options as third argument. So okey, I can fix that, based on app.isBase and app.isRegistered('base-plugins'), but there's a little problem.

So, to clarify, you created an entire plugin ecosystem and started creating new modules that either have no difference at all, or very little difference, because of a couple of very minor features? (both of which were already planned to be updated to do what you're describing. there are issues detailing these somewhere).

> I'm working on fix the compatibility issue that currently minibase-create-plugin v2 has.

lol I think the easiest way to ensure compatibility is to just use `base`. It's strange that you are creating these modules that are so similar to base and base plugins, instead of collaborating on base and offering reasoning and dialog to support the changes you want to make. It looks like you're just implementing `base` as I described in [the roadmap](https://github.com/node-base/base/issues/16), which is frustrating - especially when I have to have a discussion about "compatibility" with your competing library. This takes time away from productivity on creating docs or other things we need to get accomplished. 

cc @doowb, any opinion on this?

**Comment by tunnckoCore** [comment]
It's not about Base to be compatible with "my" shits. I'm just saying to allow `(fn, null, options)`, not changing the order or anything..

Basically there's no differences and other issues. Everything is same, everything is just Base plugin. The main thing is that I need very simpler and smaller core which Base will never accept (removing cache-base for example? in my side _absolutely everything_ is plugin on top of thin core which is just even emitter) and I'm totally okey with that, it's totally understandable - there are uses cases and reasons, okey.

As I already said in commit comment earlier today, I'm investing to Base ecosystem - there are no two ecosystems. As you see everywhere is mentioned Base and everything follow the same patterns and principles and signatures.

I started MiniBase for few not so minimal reasons and with future merge with Base in mind. As once I said somewhere in the issues: "we can use MiniBase as core for Base plus few plugins that need to be in the Base core", and it was totally possible until v2 that I'm finishing. I'm not saying such thing won't be still possible after v2, but the biggest difference in v2 is that it not uses prototypes and `this` - two core things that Base and Assemble needs and relies on. But this not means that all of the already existing dush and minibase plugins not/won't work in Base - they work, maybe want to rename them? It won't be a problem, but don't see why when each of them has `baseplugin` keyword and somewhere in their readmes Base is mentioned and linked.

Dush plugins was just started and named with `dush-*` to show the users what one plugin would look like, later just realized that I can base MiniBase on that extensible event emitter.

edit: The only things that I rely on is `app.isBase`, `app.use` and `app.isRegistered` in `minibase-create-plugin`. In other of "my libs" i just rely on `app` nothing more. You gonna change that `app` won't be the first argument of plugins?

**Comment by doowb** [comment]
@tunnckoCore I think it would be great if you would contribute to our projects by debugging issues and submitting pull requests with fixes and feature enhancements that we've discussed, instead of spending more time re-creating a lot of the modules. I know we've had some disagreements on what should be implemented, but I think that's usually due to the amount of time that @jonschlinkert and I have spent discussing things and trying out different solutions before committing the actual code.

Recently, I feel like you've been opening issues and making comments on our projects that you are actually trying to fix in the projects that you've re-created. This gives the impression that you want us to put in the work to solve something so you can use it, instead of working with us to figure out a solution.

You're also bringing up things that you're doing because of specific JavaScript features and wanting to support older node versions. These are things that some people might call bike shedding, but @jonschlinkert and I discuss all the time (because we're nerds) and have used those discussions to create libraries and make architectural decisions that abstract away these issues and make it easier to work with in other libraries.
